services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employees
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: fastapi_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app_network
  
  app:
    environment:
      WATCHPACK_POLLING: "true"
    env_file:
      - ./frontend/.env
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - db
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge